server:
  port: 8085

spring:
  application:
    name: prescription-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/db_prescriptions?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:

  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


