server:
  port: 8085

spring:
  application:
    name: prescription-service

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:db_prescriptions;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html