version: '3.8'

networks:
  hospital_net:
    driver: bridge

volumes:
  redis_data:

services:
  # ==========================================
  # INFRAESTRUCTURA BASE
  # ==========================================

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hospital_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Interfaz web de RabbitMQ
    networks:
      - hospital_net

  redis:
    image: redis:alpine
    container_name: hospital_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hospital_net

  eureka-server:
    build: ./eureka-server
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - hospital_net

  # ==========================================
  # MICROSERVICIOS
  # ==========================================
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  patient-service:
    build: ./patient-service
    container_name: patient_service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  appointment-service:
    build: ./appointment-service
    container_name: appointment_service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_started
      patient-service:
        condition: service_started

    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  doctor-service:
    build: ./doctor-service
    container_name: doctor_service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - patient-service
      - appointment-service
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_started

    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  prescription-service:
    build: ./prescription-service
    container_name: prescription_service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - appointment-service
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  inventory-service:
    build: ./inventory-service
    container_name: inventory_service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  pharmacy-service:
    build: ./pharmacy-service
    container_name: pharmacy_service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  notification-service:
    build: ./notification-service
    container_name: notification_service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  billing-service:
    build: ./billing-service
    container_name: billing_service
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - pharmacy-service
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net

  hospitalization-service:
    build: ./hospitalization-service
    container_name: hospitalization_service
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - prescription-service
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    networks:
      - hospital_net