server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: patient-service
          uri: ${PATIENT_SERVICE_URL:lb://PATIENT-SERVICE}
          predicates:
            - Path=/api/pacientes/**


        - id: appointment-service
          uri: ${APPOINTMENT_SERVICE_URL:lb://APPOINTMENT-SERVICE}
          predicates:
            - Path=/api/citas/**


        - id: doctor-service
          uri: ${DOCTOR_SERVICE_URL:lb://DOCTOR-SERVICE}
          predicates:
            - Path=/api/doctores/**


        - id: auth-service
          uri: ${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
          predicates:
            - Path=/auth/**


        - id: prescription-service
          uri: ${PRESCRIPTION_SERVICE_URL:lb://PRESCRIPTION-SERVICE}
          predicates:
            - Path=/api/prescriptions/**


        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:lb://INVENTORY-SERVICE}
          predicates:
            - Path=/api/inventario/**


        - id: pharmacy-service
          uri: ${PHARMACY_SERVICE_URL:lb://PHARMACY-SERVICE}
          predicates:
            - Path=/api/pharmacy/**


        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:lb://NOTIFICATION-SERVICE}
          predicates:
            - Path=/api/v1/notifications/**


        - id: billing-service
          uri: ${BILLING_SERVICE_URL:lb://BILLING-SERVICE}
          predicates:
            - Path=/api/v1/billing/**


        - id: hospitalization-service
          uri: ${HOSPITALIZATION_SERVICE_URL:lb://HOSPITALIZATION-SERVICE}
          predicates:
            - Path=/api/v1/hospitalizations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true