spring.application.name=presciption-service
server.port=8085
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_prescriptions
spring.datasource.username=root
spring.datasource.password=
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


