server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    # URL de H2 en memoria con compatibilidad para tus scripts de Flyway
    url: jdbc:h2:mem:patient_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Consola web de H2 para facilitar el desarrollo
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # Flyway ejecutará los scripts de db/migration al iniciar
  flyway:
    enabled: true
    locations: classpath:db/migration
    #Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html